imports:
  - { resource: news.yml }
  - { resource: @FSiDataGridBundle/Resource/datagrid/news.yml }

columns:
  actions:
    type: action
    options:
      actions:
        delete:
          route_name: fsi_admin_crud_delete
          additional_parameters: { element: news }
          parameters_field_mapping: { id: id }